### ISSUE TITLE
Received messages can no longer be seen in conversations

### ISSUE THREAD

**Issue by alehar9320** [frapperino/sketchagram#11]
Once a message has been received and the notification is pressed, only old messages can be seen.

**Comment by alehar9320** [comment]
This issue should have been in English

**Comment by ollmatt** [comment]
Vad är det som krånglar databas, modell eller server?

**Comment by alehar9320** [comment]
Scenario: Firstly, opened app on phone, minimized the app, in order to click on notification after receiving a message. Secondly, I send a message using the emulator to my phone. Then when I click the notification and get into the conversation, no new entry has been made (graphically). I.e. no new message can be seen. Only the old ones.

**Comment by ollmatt** [comment]
not a real issue
