### ISSUE TITLE
Logged in on emulator despite no connection

### ISSUE THREAD

**Issue by alehar9320** [frapperino/sketchagram#12]
Using the emulator I was able to log in on user with credentials acc: alleballe2, pw: alle123, while not getting logged in on server. This was a fresh install as well which means that it most likely isn't because of SharedPreferences.

I was also able to create a new user and log in with these credentials. There was no connection to the server at all! (as far as I could tell, visible on the users-screen, viewed as admin, on the server). No new user created, no user logged in. Nothing. On top of this I got access to the database that alleballe2 has.

Reflection: Could it be that SharedPreferences remains, despite app being uninstalled?

**Comment by ollmatt** [comment]
might be fixed
