### ISSUE TITLE
Adding is case senstivie

### ISSUE THREAD

**Issue by alehar9320** [frapperino/sketchagram#20]
Adding a new contact is case sensitive when it should not be

**Comment by ollmatt** [comment]
Should we force all usernames to be lowercase when creating them so that when a user searches we make everything lowercase as well?

**Comment by ollmatt** [comment]
Tried creating a new account called Abcd but when it was added to the server it changed it to abcd all lower case so will make the name searched for lower case before searching and it should now work when adding people
