### ISSUE TITLE
User can log in despite faulty information.

### ISSUE THREAD

**Issue by alehar9320** [frapperino/sketchagram#5]
By for example pressing log in button, the user can most often get logged in, despite lacking any entered information.

**Comment by alehar9320** [comment]
More feedback is now given to the user and simple logic-checks have been implemented on login. You can still get logged in automatically though sometimes. Not sure why. Probably because of SharedPreferences storing information.

**Comment by alehar9320** [comment]
After logging out from a valid user, it is possible to sign in again with jibberish information entered.

**Comment by ollmatt** [comment]
now works properly
